apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-exporter
  labels:
    app: sql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-exporter
  template:
    metadata:
      labels:
        app: sql-exporter
    spec:
      containers:
      - name: sql-exporter
        image: awaragi/prometheus-mssql-exporter:latest
        env:
        - name: SERVER
          value: mssql-0.meniga-getting-started.svc.cluster.local
        - name: USERNAME
          value: sa
        - name: PASSWORD
          value: rootAdmin321
        - name: DEBUG
          value: "app, metrics"
        - name: PORT
          value: "1433"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: sql-exporter
spec:
  selector:
    app: sql-exporter
  ports:
    - port: 4000
      targetPort: 4000